# Generated by Django 4.2.23 on 2025-06-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('report_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('store_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(default='America/Chicago', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=36)),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'timestamp_utc'], name='store_monit_store_i_3473c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('store_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'day_of_week'], name='store_monit_store_i_039d33_idx')],
                'unique_together': {('store_id', 'day_of_week', 'start_time_local', 'end_time_local')},
            },
        ),
    ]
